# Generated by Django 5.1.3 on 2024-11-24 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MagazineInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('publication_date', models.DateField()),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MagazineContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('vector_representation', models.JSONField()),
                ('magazine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='hybridSearch.magazineinfo')),
            ],
        ),
    ]
